# Yo! Please remember, Man!: .github/workflows/deploy-backend.yml
# Typo Error from Jaturaput-Jongsucharoen/Backend_TypeScrpt tp "Jaturaput-Jongsucharoen/Backend_TypeScript" in trust relationship of github-oidc-lambda-deploy, :Forgot b
name: Deploy Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: deploy-backend
      cancel-in-progress: true

    env:
      AWS_REGION: us-east-1
      LAMBDA_FUNCTION_NAME: backend-express
      DEPLOY_BUCKET: deploy-typescript-backend-114147526883

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json # Yo! Please remember, Man!: Feel free to adjust if My folder is different, Bro!

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prune to prod deps
        run: |
          rm -rf node_modules
          npm ci --omit=dev

      - name: Zip build
        run: zip -r function.zip dist node_modules package.json

      # --- Install AWS CLI manually (avoid action-not-found error) ---
      - name: Ensure unzip is available
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Install AWS CLI v2 (manual)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version
      # ---------------------------------------------------------------

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::114147526883:role/github-oidc-lambda-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload zip to S3
        run: aws s3 cp function.zip s3://$DEPLOY_BUCKET/backend/function-${{ github.sha }}.zip

      - name: Update Lambda code
        run: aws lambda update-function-code \
             --function-name $LAMBDA_FUNCTION_NAME \
             --s3-bucket $DEPLOY_BUCKET \
             --s3-key backend/function-${{ github.sha }}.zip \
             --publish
